name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  http: ^1.2.0
  flutter_map: ^6.1.0
  geolocator: ^14.0.2
latlong2: ^0.9.0
geolocator: ^12.0.0
flutter:
  uses-material-design: true
